"""Auto-generated strategy: v20260303_220227

Generated at: 2026-03-03T22:02:27.179805+00:00
Rationale: Auto-evolved from 9 failures. Primary failure markets: ['KR', 'US_NASDAQ']. Average loss: -17998.5
"""

from __future__ import annotations
from typing import Any
from src.strategies.base import BaseStrategy


class Strategy_v20260303_220227(BaseStrategy):
    """Strategy: v20260303_220227"""

    def evaluate(self, market_data: dict[str, Any]) -> dict[str, Any]:
            import datetime
            import pytz # For robust timezone handling

            def evaluate(self, market_data: dict) -> dict:
                # Helper for robust timezone conversion. This would typically be a utility function
                # of the BaseStrategy class, but is embedded here to strictly adhere to the "ONLY the method body" constraint.
                def _get_market_local_time(timestamp_str: str, market: str) -> datetime.datetime:
                    try:
                        dt_utc = datetime.datetime.fromisoformat(timestamp_str).astimezone(pytz.utc)
                    except ValueError:
                        # Fallback for slightly different formats or if timezone info isn't strict ISO.
                        # Assuming the most common variations for robustness.
                        dt_utc = datetime.datetime.strptime(timestamp_str.split('+')[0].split('.')[0], "%Y-%m-%dT%H:%M:%S").replace(tzinfo=pytz.utc)

                    if market == "KR":
                        # KST (Korea Standard Time) is UTC+9
                        kst_tz = pytz.timezone('Asia/Seoul')
                        return dt_utc.astimezone(kst_tz)
                    elif market == "US_NASDAQ":
                        # US_NASDAQ typically trades on Eastern Time (EST/EDT). Let's assume 'America/New_York'.
                        us_tz = pytz.timezone('America/New_York')
                        return dt_utc.astimezone(us_tz)
                    return dt_utc # Default to UTC if market not specifically handled

                # Default response: no action, low confidence, conservative rationale
                response = {
                    "action": "HOLD",
                    "confidence": 0,
                    "rationale": "Default: No compelling signal, or signal rejected by improved strategy."
                }

                # Extract relevant data from market_data
                market = market_data.get("market")
                original_action = market_data.get("action")
                original_confidence = market_data.get("confidence", 0)
                original_rationale = market_data.get("rationale", "")
                timestamp_str = market_data.get("timestamp")

                # Access nested data safely using .get()
                context_snapshot = market_data.get("context_snapshot", {})
                scenario_match = context_snapshot.get("scenario_match", {})
                input_data = market_data.get("input_data", {})

                rsi = scenario_match.get("rsi")
                volume_ratio = scenario_match.get("volume_ratio")
                price_change_pct = input_data.get("price_change_pct")

                # --- Strategy focuses on improving BUY decisions, as all failures were BUYs ---
                if original_action != "BUY":
                    # For non-BUY actions (e.g., SELL, HOLD), we assume current strategy is acceptable,
                    # or these actions are generated by different parts of the system not covered by failure analysis.
                    # Thus, we pass them through unchanged.
                    response["action"] = original_action
                    response["confidence"] = original_confidence
                    response["rationale"] = original_rationale
                    return response

                # --- Apply Filters and Adjustments for BUY Actions ---
                current_confidence = original_confidence
                rationale_modifiers = [] # Collect reasons for adjustments

                # 1. Avoid KRX market open volatility and early trading hours
                # Failures were concentrated at 00:00 UTC (09:00 KST) and early in the KRX trading day.
                if market == "KR" and timestamp_str:
                    decision_time_kst = _get_market_local_time(timestamp_str, market)
                    # KRX market opens at 09:00 KST. Avoid the first ~3 hours of trading (09:00-11:59 KST)
                    # which are typically more volatile and prone to false signals based on observed failures.
                    if 9 <= decision_time_kst.hour < 12: # From 09:00 KST to 11:59 KST
                        current_confidence = max(0, current_confidence - 30) # Aggressive confidence reduction
                        rationale_modifiers.append("Confidence significantly reduced: Buying in early KRX trading hours (high volatility observed in failures).")

                # 2. Refine "Oversold" Detection for BUYs
                # Rationale frequently claimed "oversold" when RSI was neutral (48-50), leading to losses.
                # A true oversold condition typically means RSI < 30-35.
                if "oversold" in original_rationale.lower() and rsi is not None:
                    if rsi > 40: # If RSI is not truly low (e.g., above 40)
                        # This is a critical misidentification; reject the signal immediately.
                        return {
                            "action": "HOLD",
                            "confidence": 0,
                            "rationale": f"Rejected BUY: Invalid 'oversold' signal (RSI={rsi:.2f} is not low enough). Original: {original_rationale}"
                        }
                    elif rsi > 30: # RSI between 30-40 indicates mild oversold, still potentially risky without strong confirmation.
                        current_confidence = max(0, current_confidence - 10)
                        rationale_modifiers.append(f"Confidence reduced: 'Oversold' RSI ({rsi:.2f}) is not extremely low, increasing risk.")

                # 3. Prevent Chasing Momentum (buying at peaks) / Buying Falling Knives (without strong reversal)
                if price_change_pct is not None:
                    # Avoid chasing stocks that have already surged too much.
                    # Sample failures showed buying at +25% and +22% price changes.
                    if price_change_pct > 10.0: # If stock is up more than 10% from previous close/period
                        current_confidence = max(0, current_confidence - 35) # Aggressively reduce confidence
                        rationale_modifiers.append(f"Confidence significantly reduced: Avoiding high momentum chase (Price change: {price_change_pct:.2f}%).")

                    # Avoid buying into significant dips without clear strong oversold confirmation.
                    # Sample failures showed buying at -1.2% and -2.8% price changes with neutral RSI.
                    # This catches trades where a stock is dipping, but isn't genuinely oversold to justify a rebound bet.
                    elif price_change_pct < -2.0 and (rsi is None or rsi > 30): # If it's a notable dip AND not strongly oversold
                        current_confidence = max(0, current_confidence - 20)
                        rationale_modifiers.append(f"Confidence reduced: Buying a dip ({price_change_pct:.2f}%) without strong oversold RSI confirmation.")

                # 4. General Confidence Adjustment for KR market BUYs
                # The average confidence for failed trades was 83.0, indicating the strategy was overly confident in problematic scenarios.
                if market == "KR":
                    current_confidence = max(0, current_confidence - 10) # General reduction for KR BUYs
                    rationale_modifiers.append("General confidence reduction for KR BUY signals due to historical pattern of high confidence failures.")

                    # Further penalize if high volume is a primary driver, but other indicators (like RSI) are neutral.
                    # High volume with neutral RSI often points to distribution or choppy trading rather than clear trend.
                    if volume_ratio is not None and volume_ratio > 5 and rsi is not None and 40 <= rsi <= 60:
                        current_confidence = max(0, current_confidence - 15)
                        rationale_modifiers.append("Additional confidence reduction: High volume ratio with neutral RSI in KR market signals.")

                # --- Final Decision based on Adjusted Confidence ---
                # Only proceed with a BUY if the adjusted confidence remains above a strict threshold.
                # This threshold should be higher than the average confidence of past failures (83).
                if current_confidence >= 75: # Set a conservative entry threshold
                    response["action"] = "BUY"
                    response["confidence"] = current_confidence
                    response["rationale"] = original_rationale + (" [" + "; ".join(rationale_modifiers) + "]" if rationale_modifiers else "")
                else:
                    # If confidence drops below the threshold, switch to HOLD and explain why.
                    response["action"] = "HOLD"
                    response["confidence"] = 0 # No confidence in a rejected signal
                    rejection_rationale = f"Original BUY signal rejected (adjusted confidence {current_confidence:.2f} < 75). "
                    rejection_rationale += f"Original: {original_rationale}"
                    if rationale_modifiers:
                        rejection_rationale += " [Reasons: " + "; ".join(rationale_modifiers) + "]"
                    response["rationale"] = rejection_rationale

                return response
